---
version: '3'
services:
  jupyter:
    build: '.'
    volumes:
      - './geodataset:/opt/notebooks'
    working_dir: '/opt/notebooks'
    ports:
      - '8888:8888'

  test:
    build: '.'
    environment:
      - TEST_DATA_DIR=${TEST_DATA_DIR}
      - PYTHONPATH=/
    entrypoint: /venv/bin/python
    command: "/geodataset/run_tests.py"
    volumes:
      - '${TEST_DATA_DIR}:${TEST_DATA_DIR}'

...
