name: geodataset
channels:
  - conda-forge
dependencies:
  - cartopy
  - cython
  - pip
  - pip:
    - cmocean
    - gdown
    - matplotlib
    - mock
    - netcdf4
    - netcdftime
    - numpy
    - pyproj
    - pytest
    - pyyaml
    - scipy
    - xarray
