name: geodataset
channels:
  - conda-forge
dependencies:
  - numpy==1.19.5
  - scipy==1.5.3
  - matplotlib==3.3.4
  - notebook==6.3.0
  - netcdftime==1.0.0a2
  - Cartopy==0.19.0.post1
  - satpy==0.26.0
  - coverage==5.5
