name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      env:
        CACHE_NUMBER: 1
      with:
        path: |
          /usr/share/miniconda3/envs
          /home/runner/work/test_data
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('environment_testing.yml') }}
      id: cache
    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment_testing.yml
        miniforge-version: latest
        activate-environment: geodataset_testing
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Install extra packages for testing
      run: |
          pip install netcdftime pytest gdown
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Test with pytest
      run: |
        mkdir -p /home/runner/work/test_data
        gdown https://drive.google.com/uc?id=1NmJeldiS5XlIwciDhej8Mas8g1Ng9T6n -O /home/runner/work/test_data/
        gdown https://drive.google.com/uc?id=1j1zkyNDM9EwcvgipMskhuRDoe6mYBhnN -O /home/runner/work/test_data/
        gdown https://drive.google.com/uc?id=1GvwVxIPi4S_0uJDiSeXURYKu8fCQlLxx -O /home/runner/work/test_data/
        gdown https://drive.google.com/uc?id=1S0OLfr6DdJIflZC6mVbYTjKHj4XZ4TKg -O /home/runner/work/test_data/
        gdown https://drive.google.com/uc?id=1RD9V1iS-tS0QIdg2IUyX_KR4PK3SpbFl -O /home/runner/work/test_data/
        gdown https://drive.google.com/uc?id=1KGapeF6EG4h8gGPxNbkyRnRBYu3i7bdD -O /home/runner/work/test_data/
        gdown https://drive.google.com/uc?id=1dRo0gfoJCinnOhA96YQpqnddhbdW_Z09 -O /home/runner/work/test_data/
        gdown https://drive.google.com/uc?id=1JReSKt2nBKAf9mRwrbnoLQPewFqK2l93 -O /home/runner/work/test_data/
        gdown https://drive.google.com/uc?id=1c1nyBFjNuM8njurt5FcK49Bz14R_O2Jx -O /home/runner/work/test_data/
        pytest
      env:
          TEST_DATA_DIR: /home/runner/work/test_data/

