name: Python Package using Conda

on:
  push:
  release:
    types: [released]

jobs:
  test:
    needs: get_test_data
    runs-on: ubuntu-latest
    container:
      image: nansencenter/geodataset_base:latest
      env:
        TEST_DATA_DIR: /netcdf
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ container.env.TEST_DATA_DIR }}
          key: 0
      - name: Download test data
        run : |
          mkdir -p $TEST_DATA_DIR
          gdown https://drive.google.com/uc?id=1NmJeldiS5XlIwciDhej8Mas8g1Ng9T6n -O $TEST_DATA_DIR/
          gdown https://drive.google.com/uc?id=1j1zkyNDM9EwcvgipMskhuRDoe6mYBhnN -O $TEST_DATA_DIR/
          gdown https://drive.google.com/uc?id=1GvwVxIPi4S_0uJDiSeXURYKu8fCQlLxx -O $TEST_DATA_DIR/
          gdown https://drive.google.com/uc?id=1S0OLfr6DdJIflZC6mVbYTjKHj4XZ4TKg -O $TEST_DATA_DIR/
          gdown https://drive.google.com/uc?id=1RD9V1iS-tS0QIdg2IUyX_KR4PK3SpbFl -O $TEST_DATA_DIR/
          gdown https://drive.google.com/uc?id=1KGapeF6EG4h8gGPxNbkyRnRBYu3i7bdD -O $TEST_DATA_DIR/
          gdown https://drive.google.com/uc?id=1dRo0gfoJCinnOhA96YQpqnddhbdW_Z09 -O $TEST_DATA_DIR/
          gdown https://drive.google.com/uc?id=1JReSKt2nBKAf9mRwrbnoLQPewFqK2l93 -O $TEST_DATA_DIR/
          gdown https://drive.google.com/uc?id=1c1nyBFjNuM8njurt5FcK49Bz14R_O2Jx -O $TEST_DATA_DIR/
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Check data dir content
        run: ls -l $TEST_DATA_DIR/
      - uses: actions/checkout@v2
      - name: Test with pytest
        run: |
          pytest
  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v2
