name: Python Package using Conda

on:
  push:
  release:
    types: [released]

jobs:
  get_test_data:
    runs-on: ubuntu-latest
    steps:
      - name: Install gdown
        run: |
          pip install gdown 
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /home/runner/work/test_data
          key: 0
        id: cache
      - name: Download test data
        run : |
          mkdir -p /home/runner/work/test_data
          gdown https://drive.google.com/uc?id=1NmJeldiS5XlIwciDhej8Mas8g1Ng9T6n -O /home/runner/work/test_data/
        if: steps.cache.outputs.cache-hit != 'true'
  test:
    needs: get_test_data
    runs-on: ubuntu-latest
    container:
      image: nansencenter/geodataset_base:latest
      env:
          TEST_DATA_DIR: /netcdf
      volumes:
        - /home/runner/work/test_data:/netcdf
    steps:
      - uses: actions/checkout@v2
      - name: Test with pytest
        run: |
          pytest
  publish:
    needs: test
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v2
