name: Python Package using Conda

on:
  push:
  release:
    types: [released]

jobs:
  test-build-publish:
    runs-on: ubuntu-latest
    container:
      image: nansencenter/geodataset_base:latest
      env:
          TEST_DATA_DIR: /home/runner/work/test_data/
    steps:
    - uses: actions/checkout@v2
    - name: Download test data
      run: |
        mkdir -p /home/runner/work/test_data
        gdown https://drive.google.com/uc?id=1NmJeldiS5XlIwciDhej8Mas8g1Ng9T6n -O /home/runner/work/test_data/
    - name: Test with pytest
      run: |
        echo $TEST_DATA_DIR
        which pytest
        pytest
